match cache size to request
sourcegraph/deploy-sourcegraph pull request #2369
Opened 2021-04-09 16:29 UTC by davejrt

We should match the size of the cache to the default request for ephemeral storage.

2021-04-29 22:44 UTC, daxmc99 reviewed
I would personally prefer we raise the requests to this value. Decreasing it may have unintended consequences

2021-05-05 17:29 UTC, davejrt commented
@daxmc99 I've increased the requests and limits. Do you off hand know if having the request/limit set to the same value would result in this always being evicted? I suspect we should allow some some burst right?

2021-05-05 22:09 UTC, daxmc99 requested changes
I think this makes the most sense. 
This will make 10GB a requirement to schedule the pod though. 
The pod will only be evicted if it reaches 12 GB 
We should document this in the changelog

2021-05-05 22:09 UTC, daxmc99 commented on base/symbols/symbols.Deployment.yaml
> +            ephemeral-storage: "10Gi"
```suggestion
            ephemeral-storage: "10G"
```

2021-05-05 22:09 UTC, daxmc99 commented on base/symbols/symbols.Deployment.yaml
> +            ephemeral-storage: "12Gi"
```suggestion
            ephemeral-storage: "12G"
```

2021-05-06 15:58 UTC, merged